name: myapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  connectivity: ^0.4.2
  http: ^0.12.0+1
  progress_hud: ^1.1.0
  after_layout: ^1.0.7
  sqflite: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true